gemfile:
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
install:
  - 'travis_retry bundle install'
language:
  - ruby
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails3.1.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails3.1.gemfile
rvm:
  - 2.0.0
  - 2.1.2
script: 'bundle exec rake spec'
